theme: jekyll-theme-hacker

title: Home
description: Just a crazy developer who strive to be lazy. I'm a vim addicted and a completely Linux xiita.
twitter:
  username: marinofull
  description: Just a crazy developer who strive to be lazy. I'm a vim addicted and a completely Linux xiita.
